POST http://localhost:8080/api/save
Content-Type: application/json

{
  "username": "1",
  "password": "2",
  "country":"3"
}


####

POST http://localhost:8080/api/list
Content-Type: application/json

{
"username": "1",
"password": "2",
"country":"3"
}